arb-dir: lib/src/l10n/arb
template-arb-file: intl_en.arb
output-localization-file: localizations.g.dart
output-class: TCoreL10n
nullable-getter: false
output-dir: lib/src/l10n/generated
synthetic-package: false
