name: tcore
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  intl: any
  meta: ^1.9.1
  nested: ^1.0.0
  signed_spacing_flex: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
